title:            Kevin Zou
description: Job Market Candidate
site_title: 'Kevin Zou, Job Market Candidate'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: KevinKCV
github_username: 
email: zou@vt.edu

# absolute or relative
profile_picture: assets/images/kz.jpg

# Google Analytics ID
google_analytics: 
