title: Chang Geun Song
description: Ph.D. Candidate, Economics, Virginia Tech
site_title: '@Chang Geun Song, Ph.D. candidate'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: cgsongv
email: cgsong86@vt.edu

# absolute or relative
profile_picture: assets/images/pp3.jpg

# Google Analytics ID
google_analytics: 
